### PR TITLE
Add seoul256 scheme for lightline.vim

### PR DESCRIPTION
**Pull request by atweiden**
adds support for [seoul256](https://github.com/junegunn/seoul256.vim)

scrot

### CODE REVIEW

**Comment by itchyny** [comment]
You use `#af5f5f` and `#87af87` in the colorscheme but I could find none of them in https://github.com/junegunn/seoul256.vim/blob/master/colors/seoul256.vim. Where did you pick the colours from?

**Comment by atweiden** [comment]
- color #87af87 is from [Xresources](https://github.com/junegunn/seoul256.vim/blob/master/urxvt/seoul256#L15)
- color #af5f5f is from [CursorLineNr](https://github.com/junegunn/seoul256.vim/blob/master/colors/seoul256.vim#L194)

CursorLineNr

**Comment by atweiden** [comment]
`#87afaf` and `d0d0d0` are from xresources

tmux in urxvt (seoul256)

**Comment by itchyny** [comment]
Thanks for your contribution.

**Pull request merged**
