### PR TITLE
Added retrobox colorscheme from https://github.com/vim/colorschemes/

### LINKED ISSUE #643: Please consider the retrobox colorscheme in the flavor of gruvbox
Hi. Thank you for the awesome plugin. As the lightline.vim provides many themes and the popular color schemes provide lightline.vim theme in its own repository, I had never wanted to do such a request for lightline.vim. However, the situation is changed these days, because vim officially added a new built-in color scheme, [retrobox] in the flavor of grubvox8.

We may not be able to request vim to support the external plugin (lightline.vim) as the built-in color scheme is designed minimally to support built-in functionalities. The motivation of this issue comes from this policy. I thought lightline.vim should/ would support the popular or built-in color scheme at least.

Please consider adding the retrobox color theme for the lightline.vim. Thanks.

[retrobox]: https://github.com/vim/colorschemes/pull/217

### PR DESCRIPTION
**Pull request by prateektade**
Fixes #643.

I have used the colors from the [retrobox](https://github.com/vim/colorschemes/blob/master/colors/retrobox.vim) colorscheme and the logic from the [gruvbox](https://raw.githubusercontent.com/morhetz/gruvbox/master/autoload/lightline/colorscheme/gruvbox.vim) lightline colorscheme.

I tried to add the screenshots but couldn't figure out how to update the wiki, so attaching the screenshots here -

## Retrobox (`background=light`)
Retrobox_Light

## Retrobox (`background=dark`)
Retrobox_Dark

### CODE REVIEW

**Comment by itchyny** [comment]
When including a newer colorscheme to this repository, it's required to follow the rules in the last sentence of `:h lightline-colorscheme`. Also, use `lightline#colorscheme#background()` instead of `&background`, and remove checking the existence of `g:lightline` because it's totally useless.

**Comment by prateektade** [comment]
Changes made as per contributing guidelines. Updated screenshots below -

## Retrobox (`background=dark`)
Retrobox_New_Dark

## Retrobox (`background=light`)
Retrobox_New_Light

**Comment by tani** [comment]
That's awesome code. Thanks!
Retrobox provides the colorscheme for: termguicolors, 256colors, 16colors, 8colors.
Is it possible to support all the above situations?

**Comment by prateektade** [comment]
> That's awesome code. Thanks! Retrobox provides the colorscheme for: termguicolors, 256colors, 16colors, 8colors. Is it possible to support all the above situations?

Thanks for your kind words.

I don't fully know Vim script so I am not sure how I can explicitly declare the values for all 4 formats, but looking at all the other color schemes I see the `termguicolors` and `xterm256-colors` being declared so I have followed the same.

**Comment by itchyny** [comment]
It seems that vim-gruvbox8 is licensed under Vim License which is GPL-compatible so I'm afraid I cannot include this repository (sorry, I'm not a lawyer so this is just a guess). I've already read this PR code and I can't write and include the colorscheme myself. I'll check if anyone else will send me different patch based on the code inside this repository.

**Pull request closed without merging**
