### PR TITLE
Add srcery_drk colorscheme

### PR DESCRIPTION
**Pull request by chrisvittal**

### CODE REVIEW

**Comment by itchyny** [comment]
May I flip the colors of normal and insert modes?

**Comment by chrisvittal** [comment]
I went ahead and did it. It makes these colors more consistent with the rest of the plugin.

**Comment by itchyny** [comment]
Ah, thanks. Can you fix the inconsistent spacing of arrays?

**Comment by itchyny** [comment]
Thank you.

**Pull request merged**
