### PR TITLE
Change tabline's background color of solarized theme (Close #135)

### LINKED ISSUE #135: Wrong TabLine color with solarized_dark theme
Hi there,

I've noticed a strange behavior with my neovim setup. I use lightline with solarized_dark colorscheme enabled, but when I would open a new tab, the TabLineFill parameter in vim would show a solarized_light background. 

Here's a screenshot to explain what I mean:
solarized_problem

I fixed that by changing a parameter in solarized_dark inside lightline's colorscheme folder. Now it looks like this:
solarized_fix

I'll include a pull request with my edit in case that's something that needs to be included in the repo.

Thanks.

### PR DESCRIPTION
**Pull request by alexeyzab**
To fit solarized_dark's colorscheme

https://github.com/itchyny/lightline.vim/issues/135

### CODE REVIEW

**Comment by itchyny** [comment]
Okay, TabLineFill colour looks wrong actually and your fix seems to be reasonable. However, now it is difficult to find the border between TabLineSel and TabLineFill. Would you please tweak the colour of TabLineSel (s:p.tabline.middle)?

**Comment by alexeyzab** [comment]
Sure! I am not entirely sure what to change it to, since I've been mostly trying to make it look the same as my vim (no lightline):
vim-look

But I agree that that kind of color makes TabLineSel and TabLineFill blend. So I started experimenting and made this:
nvim-new-look

Let me know what you think. Blue color for selected tab makes it more distinct and also fits in the overall solarized dark theme.

**Comment by itchyny** [comment]
It looks too vivid...

How about the following colours?
```
let s:p.tabline.left = [ [ s:base1, s:base00 ] ]
let s:p.tabline.tabsel = [ [ s:base3, s:base0 ] ]
let s:p.tabline.middle = [ [ s:base01, s:base02 ] ]
```

**Comment by alexeyzab** [comment]
Looks good to me! I'll set those and make a pull request now. Thanks for helping!

**Comment by itchyny** [comment]
Thank you for your pull request.

**Pull request merged**
