### PR TITLE
Added functional.vim color theme.

### PR DESCRIPTION
**Pull request by L0stLink**
Added functional.vim color theme, which is based on the Dracula color pallet (https://github.com/dracula/dracula-theme#color-palette).

### CODE REVIEW

**Comment by L0stLink** [comment]
Don't know if it is necessary but here is what it looks like:
Normal Mode:
selection_2019_09_24_22_24_45
Insert Mode:
selection_2019_09_24_22_25_06
Replace Mode:
selection_2019_09_24_22_25_21
Visual Selection Mode:
selection_2019_09_24_22_25_38
With Linting support:
selection_2019_09_24_22_31_52

**Comment by itchyny** [comment]
I prefer the name of lightline colorscheme is taken from a colorscheme but I suspect there's no colorscheme named functional.

**Comment by L0stLink** [comment]
This is a custom color theme that I assembled for my personal use, I liked the color pallet of dracula color theme but disagreed with the color application, as there is already a dracula color theme for lightline, so I could not use that name. Consider it a new color theme (some colors are different so it cannot be considered a direct replacement anyway).

**Comment by itchyny** [comment]
I don't want to include a new lightline colorscheme which isn't based on Vim colorscheme so closing. There are [many third party lightline colorscheme](https://github.com/search?q=lightline+colorscheme&type=Repositories) so please consider distribute from your repository. Thanks.

**Pull request closed without merging**
